name : newman API Tests
on: 
  push:
    branches: ["main"] 
jobs:
  run-api:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: installation de Node jobs
        uses: action/setup-Node@4
        with:
          node-version: "18"


    